name: Update FlightRadar TRMNL

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-flight-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      env:
        FLIGHT_RADAR_API_KEY: ${{ secrets.FLIGHT_RADAR_API_KEY }}
        TRMNL_ENDPOINT_URL: ${{ secrets.TRMNL_ENDPOINT_URL }}
        STREET: ${{ secrets.STREET }}
        CITY: ${{ secrets.CITY }}
        COUNTRY: ${{ secrets.COUNTRY }}
        STATE: ${{ secrets.STATE }}
        POSTALCODE: ${{ secrets.POSTALCODE }}
        GEOCODE_KEY: ${{ secrets.GEOCODE_KEY }}
        GOOGLE_SE_ID: ${{ secrets.GOOGLE_SE_ID }}
        GOOGLE_SE_KEY: ${{ secrets.GOOGLE_SE_KEY }}
        OPENSKY_CLIENT_ID: ${{ secrets.OPENSKY_CLIENT_ID }}
        OPENSKY_CLIENT_SECRET: ${{ secrets.OPENSKY_CLIENT_SECRET }}
      run: |
        python sendWebhook.py
